version: 2.1
orbs:
  cypress: cypress-io/cypress@1
  node: circleci/node@3.0.0
workflows:
  build:
    jobs:
      - cypress/run:
          install-command: 'npm install --no-package-lock --no-optional'
          start: 'npm run build:test'
          wait-on: 'http://localhost:3000/'
